# Generated by Django 4.1.4 on 2023-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0007_homesilder_remove_blog_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('custom_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
