# Generated by Django 4.1.4 on 2024-02-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='images/FundRaise/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
